/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package packet;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.ImageObserver;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author bebee
 */
public class Ventana extends javax.swing.JFrame {
    Conector con = new Conector();
    private String palabra;
    private Timer t;
    
    /** Creates new form Ventana */
    public Ventana() {
        initComponents();
        con.conectar();
        
        /*ImageIcon imagen = new ImageIcon("src/res/redbull.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(img_redbull1.getWidth(), img_redbull1.getHeight(), Image.SCALE_DEFAULT));
        img_redbull1.setIcon(icono);
        
        ImageIcon imagen2 = new ImageIcon("src/res/redbull.jpg");
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(img_redbull2.getWidth(), img_redbull2.getHeight(), Image.SCALE_DEFAULT));
        img_redbull2.setIcon(icono2);*/
        
        ImageIcon fondoxd = new ImageIcon("src/res/fondo.png");
        Icon icono3 = new ImageIcon(fondoxd.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(icono3);
        
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        INICIAR = new javax.swing.JButton();
        PARAR = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(747, 519));
        setMinimumSize(new java.awt.Dimension(747, 519));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 100, 740, 62);

        INICIAR.setText("Iniciar");
        INICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIARActionPerformed(evt);
            }
        });
        getContentPane().add(INICIAR);
        INICIAR.setBounds(170, 410, 200, 54);
        INICIAR.getAccessibleContext().setAccessibleParent(INICIAR);

        PARAR.setText("PARAR");
        PARAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PARARActionPerformed(evt);
            }
        });
        getContentPane().add(PARAR);
        PARAR.setBounds(430, 410, 200, 54);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/fondo.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 740, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIARActionPerformed
        INICIAR.setEnabled(false);
        palabra();
        t = new Timer(10000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                palabra();
            }
        });
        t.start();
    }//GEN-LAST:event_INICIARActionPerformed

    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        con.cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void PARARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PARARActionPerformed
        t.stop();
        INICIAR.setEnabled(true);
    }//GEN-LAST:event_PARARActionPerformed

   private void palabra(){
        palabra = con.getAleatorio();
        jLabel1.setText(palabra.toUpperCase());
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INICIAR;
    private javax.swing.JButton PARAR;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
